application: johannesfilter
version: 5
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: blog.py

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
